# curl -u ft:12345 -v -X POST --data-binary @RTPe.lzh -H "Content-Type: application/x-lzh-compressed" http://localhost:8080/vapor/game
POST http://localhost:8080/vapor/game
Authorization: Basic ft 12345
Content-Type: application/x-lzh-compressed

< C:\Users\Anwender\Desktop\Neuer Ordner\SAMPLE GAME.lzh

###

